### PR TITLE
Topic/allow search with pip

### PR DESCRIPTION
**Pull request by blade2005**
Example output
```
$ pip search --index http://127.0.0.1:8092 pypiserver
pypiserver                - 1.2.0.dev1
  INSTALLED: 1.2.0.dev1 (latest)
$ pip search --index http://127.0.0.1:8092 pypiserver9
$ 

```

The two additional libs in use are both part of standard python.

However unit testing hasn't been added yet. Trying to figure out how to get WebTest to understand and send xml

### CODE REVIEW

**Comment by mplanchard** [comment]
I like this. Is there any way you could add a unit test for the added functionality?

**Comment by blade2005** [comment]
Thats on my list of things to do. I've just been super busy and need to sit down and understand how the testing framework is set up so I can emulate the rpc request.

**Comment by mplanchard** [comment]
Glad to hear it, and there's no rush. Let me know if there's any way I can help.

**Comment by mplanchard** [comment]
@blade2005  The PR against your branch contains a test for the search functionality. This doesn't address the issue where `test_server` is hanging on Travis for some reason. I'm looking into that now.

**Comment by mplanchard** [comment]
I'm going to ahead and merge this

**Pull request merged**
