### PR TITLE
Specify doctype for generated pages.

### LINKED ISSUE #412: After I have upgraded pip to 22.0, pypiserver started to occur; HTML doctype missing or incorrect. Expected  <!DOCTYPE html>.
After I have upgraded pip to 22.0, pypiserver started to occur the following error. (I use python 3.8)
```
ValueError: HTML doctype missing or incorrect. Expected <!DOCTYPE html>.

If you believe this error to be incorrect, try passing the command line option --use-deprecated=html5lib and please leave a comment on the pip issue at https://github.com/pypa/pip/issues/10825.
```

### PR DESCRIPTION
**Pull request by domdfcoding**
This ensures compliance with PEP 503

Fixes #412

### CODE REVIEW

**Review by mv1005 — APPROVED** [review]
I tested the changes against pip 22.0.1 and it worked like a charme. Checking with `wget` confirms that `DOCTYPE` is now present.

**Comment by mv1005** [comment]
I just saw that a new version of pip (22.0.2) is available, which throws a warning instead of aborting in case the page returned by the server is not well formed regarding the HTML 5 rules.

Unfortunately, even with your fix applied, pip 22.0.22 still issues a warning telling that the document "is not a proper HTML 5 document". So at least from the perspective of pip (or python), the page still seems not to be HTML 5 conform.

If the goal of this fix is to ensure compliance with PEP 503 (which says "valid HTML 5") the HTML 5 conformance of the generated pages should be verified with some external tool.

**Comment by domdfcoding** [comment]
I checked the generated pages with https://validator.w3.org/nu/ . It shows a warning for a missing `lang` attribute but no errors.

If I use pip==22.0.1 there's no warning about the page not being HTML 5, so I think there might have been a regression in pip.

**Comment by mv1005** [comment]
Indeed, I observed the same behaviour and was not sure how to interprete the results.

Am 31. Januar 2022 10:17:25 MEZ schrieb Dominic Davis-Foster ***@***.***>:

**Comment by domdfcoding** [comment]
pypa/pip#10855 should solve the issue with pip

**Review by g3n35i5 — APPROVED** [review]

**Review by barrieca — APPROVED** [review]
Looks good 👌

**Review by Kaldor37 — APPROVED** [review]
Looks good to me !

**Comment by dee-me-tree-or-love** [comment]
Hey everyone! First of all sorry for the lack of activity from my side on accepting, and thanks for submitting the PR and the discussion. I think a different PR (#414) was submitted focusing on the exact same issue and I have just merged it into the `master` branch since it came across my sight! Extremely sorry because this Pull Request was clearly submitted earlier and I really appreciate the community discussion here! I think that the current state of the file should be identical. I will merge it nonetheless to make justice for the submission :)

**Review by dee-me-tree-or-love — APPROVED** [review]

**Comment by tahigash** [comment]
@dee-me-tree-or-love any plan to release new version of pypiserver package with this fix? I would like to know when it's coming.

**Comment by dee-me-tree-or-love** [comment]
Hello @tahigash! Thanks a lot for the poking, I've just recently communicated the access to the release procedures with @mplanchard and will be setting it up in the coming days. I hope to be ready by the end of this week with something working, so that the new features are made available :) Thanks for checking and sorry for all the waiting!

**Comment by tahigash** [comment]
@dee-me-tree-or-love thanks for quick reply! as long as new release has being planned. I'm glad to hear that. :D

**Comment by dee-me-tree-or-love** [comment]
Hey, @tom-dalton-fanduel no worries, and thanks for poking me! That's indeed a very valid question and I am sorry I've been so slow in getting the releases up. As of now, I am aiming to release a new version (I am in doubt whether to make it 2.0.0 or an intermediate 1.5.0) within a short time (I've been a little bit swamped with the current surroundings and that's indeed getting delayed). I have created an issue that can serve as an open discussion space for the next release preparations (#419). I suggest, if we could further lead the discussion about it there, that'd be great (also making it easier to find for the rest!), hope that this will help to provide some indications. All the comments and suggestions are super welcome! Sorry once again for the slow pace!

**Pull request merged**
