### PR TITLE
Add Python 3.5 Support (#108)

### PR DESCRIPTION
**Pull request by mplanchard**
Resolves Issue #108 

There's some overlap here with issue #107 - I went ahead and removed the old Python versions from the test suite. Otherwise updated to build and test on Python 3.5.

The only weirdness was that Python 3.5 required `wheel >= 0.25.0`, or certain aspects of the install would fail, so it has been added to the test requirements in setup.py and specified in `requirements/dev.pip`.

### CODE REVIEW

**Comment by ankostis** [comment]
I see that you merged with my `dev`, but missed most the changes; so better `reset --hard` on my `dev`, it already contains your important py3.5 commit.

Hint: When you want to rewrite a branch that a PR is relied upon with, you just do it with `git push -f`, no need to open a new PR in GH (i.e. 108 & 110).

**Comment by ankostis** [comment]
Are we ok, to merge it in pypiserver/master and close it?

**Comment by ankostis** [comment]
Merge into master.

**Comment by mplanchard** [comment]
Awesome. Thanks!

**Comment by ankostis** [comment]
Me too :-)

**Pull request closed without merging**
