### PR TITLE
Fix url in welcome template.

### PR DESCRIPTION
**Pull request by michaelkuty**
fixed urls in links

```
<html><head><title>Welcome to pypiserver!</title></head><body>
<h1>Welcome to pypiserver!</h1>
<p>This is a PyPI compatible package index serving 86 packages.</p>

<p> To use this server with pip, run the the following command:
<blockquote><pre>
pip install -i http://10.10.10.122:9000/unstable/simple/ PACKAGE [PACKAGE2...]
</pre></blockquote></p>

<p> To use this server with easy_install, run the the following command:
<blockquote><pre>
easy_install -i http://10.10.10.122:9000/unstable/simple/ PACKAGE
</pre></blockquote></p>

<p>The complete list of all packages can be found <a href="packages/">here</a> or via the <a href="simple/">simple</a> index.</p>

<p>This instance is running version 1.0.0 of the <a href="http://pypi.python.org/pypi/pypiserver">pypiserver</a> software.</p>
</body></html>
```

### CODE REVIEW

**Comment by mplanchard** [comment]
Hello, and thanks for contributing to `pypiserver`. Could you please expound a bit on the system on which you're seeing this bug? The changed link functionality works fine on my setup, and generates functional URLs that link to the package lists:

````
<html><head><title>Welcome to pypiserver!</title></head><body>
<h1>Welcome to pypiserver!</h1>
<p>This is a PyPI compatible package index serving 71 packages.</p>

<p> To use this server with pip, run the the following command:
<blockquote><pre>
pip install --extra-index-url https://pypi.i2.ihiji.net/ PACKAGE [PACKAGE2...]
</pre></blockquote></p>

<p> To use this server with easy_install, run the the following command:
<blockquote><pre>
easy_install -i https://pypi.i2.ihiji.net/simple/ PACKAGE
</pre></blockquote></p>

<p>The complete list of all packages can be found <a href="/packages/">here</a>
or via the <a href="/simple/">simple</a> index.</p>

<p>This instance is running version 1.1.10 of the
  <a href="http://pypi.python.org/pypi/pypiserver">pypiserver</a> software.</p>
</body></html>
````

**Comment by michaelkuty** [comment]
Problem is with paste.ini

http://pypi.robotice.org/
http://pypi.robotice.org/unstable

on second link are wrong urls in links but in pip install command is ok because uses url instead of new path..

**Comment by mplanchard** [comment]
Ah, I see. I will try to look into this in more depth when I find some time, but the proposed fix causes several tests [to fail](https://travis-ci.org/pypiserver/pypiserver/jobs/117034453). We may need to either adjust the fix or adjust the tests to reflect the changes. Are you able to spend some time working on that?

**Comment by ankostis** [comment]
@michaelkuty can you rebase on master?
#141 fixes the CI failure.

Also can you check without your fix if `paste` now works OK due to the redirection fix(#140)?

**Comment by mplanchard** [comment]
Looks like all tests are still failing even with #141 being fixed. Please update with the status of the bug now that #140 is merged when you have time, @michaelkuty.

**Comment by mplanchard** [comment]
@ankostis I vote that we close this PR, as we have neither been able to replicate and have not had a response on the current status in some time.

**Comment by mplanchard** [comment]
Closing due to lack of response. Feel free to re-open with new information or responses to questions.

**Pull request closed without merging**
