### PR TITLE
Build docker images for multi arch

### LINKED ISSUE #364: Official Docker image support for ARM?
Hi Pythonistas, I want to port our private PyPI server Docker container to ARM. But I found the official build on Docker Hub only supports amd64. Is there any plan for ARM support?

Reference:
https://hub.docker.com/r/pypiserver/pypiserver

### PR DESCRIPTION
**Pull request by isac322**
Fixes #364 

I list up all arches of [python:3.8-alpine3.12](https://hub.docker.com/_/python?tab=tags&page=1&ordering=last_updated&name=3.8-alpine3.12).

And I followed https://github.com/docker/setup-qemu-action

### CODE REVIEW

**Comment by mplanchard** [comment]
Thanks for this PR! Just FYI I'm extremely busy right now w/work and a few things that have come up outside of work, so it will be probably a couple of weeks before I can get back to reviewing PRs. I will get to them as soon as possible!

**Comment by isac322** [comment]
@mplanchard Gentle reminder

**Comment by dee-me-tree-or-love** [comment]
Hi @isac322, thanks for submitting the pull request and your reminder! This sounds like a very useful and important addition to me! @mplanchard has unfortunately been a little too busy recently, and I am trying to pick up the reviewing a little bit more instead. I will try to get back to this asap within the coming week or two. Thanks for your patience ✌️👍

**Comment by mowirth** [comment]
@dee-me-tree-or-love 

Hey, are there any updates on this PR? If you have additional commands or require any help, please let me know.

**Comment by dee-me-tree-or-love** [comment]
> @dee-me-tree-or-love
> 
> Hey, are there any updates on this PR? 

Hey @mowirth thanks a lot for the kind reminder! Sadly I was unable to take a look at the PRs and issues lately due to moving between cities and this one got lost in my stack of todos, so thank you for the ping. But I do really hope to get to it in the near future! 🙏 

> If you have additional commands or require any help, please let me know.

And thank you for the offer! If you feel like taking a deeper look into this yourself, please be welcome! I'll really appreciate any comments and suggestions from your side and will use them once I get to this - it would definitely augment and can speed up my understanding of the impacts :) But only if you do feel like! 🍀 😉

**Comment by dee-me-tree-or-love** [comment]
Hello @isac322, I'm sorry for such a long radio silence! 

I have recently managed to merge #553 from @cbwchuck [which bumps the action versions and includes the docker builds for `arm64` + `amd64`](https://github.com/pypiserver/pypiserver/issues/468#issuecomment-1987331266). I found it a very good starting point and I'm sorry I haven't visited your PR earlier. 

If you are still interested, would you like to take a look and update your branch again?

Let me know, if not that's totally cool too, I'll try to get this merged in a feature-branch fashion sometime this summer. 

Thanks a lot for your patience and help in either case ❤️

**Pull request closed without merging**
