### PR TITLE
Add Cache-control header to enable pip caching

### PR DESCRIPTION
**Pull request by bartekrychlicki**
Please have a look at [pip 6 cache documentation](http://pip.readthedocs.org/en/stable/reference/pip_install.html?highlight=CacheControl#caching).

I wrote tests but I am not sure if they fit your conventions, sorry.

### CODE REVIEW

**Comment by ror6ax** [comment]
Thanks a lot for the help, I will review and merge asap.

**Comment by ankostis** [comment]
@bartekrychlicki  may i make the merge with the welcome-msg?

**Comment by bartekrychlicki** [comment]
I messed up, I misunderstood how github works and rewrote history. I will solve this in about 8h.
Yes, @e946755 should have gone to a different branch. I will put history back to its pre-mess state and then later on. Sorry.

**Comment by ankostis** [comment]
Nessun problema ;-)

You can rewrite anythning in github.  
I would go for a rebase of your PR onto pypiserver/master.
But it is always challenging to try things yourself, i'm also new into all these and still learning them the hard way.

**Comment by bartekrychlicki** [comment]
@ankostis Fixed. I just removed the two commits with that another feature I wanted and moved them to a separate branch. All back to normal. 

Ready to be merged. 

As a side note, this cache-control feature is useless with newest PIP, an undocumented but visible in the code part requires server to be SSL certified for cache to work. The previous cache in pip was fine and they "fxied" things :). This will be useful for people with certificate though :).

**Comment by ankostis** [comment]
Transfered in cachectrl@ankostis #74 and merged.

**Pull request closed without merging**
