### PR TITLE
Deprecate cgi module to support python3.13

### PR DESCRIPTION
**Pull request by matteius**
Deprecate cgi module to support python3.13

### CODE REVIEW

**Comment by oz123** [comment]
Please instead of insitu forking,  vendor the new version of bottle that was released a few days ago.

**Comment by matteius** [comment]
Apparently bottle is vendor'd and they fixed this a couple days ago -- so while this PR is probably not the right approach, I am requesting we figure out how to fix it.

**Comment by matteius** [comment]
D'oh my comment I deleted it by mistake -- yes, we should take the right approach to vendor newer bottle--I didn't realize it was a vendored dependency.

**Comment by dee-me-tree-or-love** [comment]
@matteius @oz123, thanks a lot for the PR and discussion! Indeed, making `bottle` a proper dependency is really needed 👍 If you would like to propose a PR, I'll be happy to review! ⭐ 

Otherwise I'll try to find the time to address this issue in the coming month, sorry for the waiting time ✌️

**Comment by dee-me-tree-or-love** [comment]
FYI: This issue #604 by @mgorny seems very related :v:

**Comment by dee-me-tree-or-love** [comment]
Hello @matteius wanted to give a quick update! With https://github.com/pypiserver/pypiserver/pull/619 (big thanks to @oz123!) we have updated Bottle to the newer version altogether, so it should now support Python 3.13 correctly. 

We still aim to make it correctly vendored as a regular dependency in the near future, so if you'd like to give it a try, please feel welcome! I'll appreciate all and help in this 😇 🙏  

Thanks a lot for your PR and effort again! ⭐ 
Since we're now running on a newer bottle, I'll close this PR, feel free to reopen or reach back if you'd like.

**Pull request closed without merging**
