### PR TITLE
Add a separate cache for file digests

### PR DESCRIPTION
**Pull request by virtuald**
Turns out, those file digests get really annoying if you have a hundred or so packages that are 40mb each (don't ask... ). This improves the cache and makes that less annoying.

### CODE REVIEW

**Comment by ankostis** [comment]
Nice,
Just describe a bit more in the commit message and/or here why #101 was not enough, and what does this differently.
I don't have any experience with such heavy loads.

**Comment by virtuald** [comment]
Updated the commit, should work now...

**Comment by virtuald** [comment]
Also added a fix for --hash-algo=off in here, in case someone decides that approach is better for them.

**Comment by ankostis** [comment]
Very well!

(are you still insisting not to participate to `pypiserver` team?)

**Comment by virtuald** [comment]
Yep. Just because I don't want to be on the team doesn't mean that I won't fix issues that affect me. :)

**Comment by mplanchard** [comment]
Can we get unit tests for the new caching functionality?

If not, I'll look into adding some this weekend.

**Comment by ankostis** [comment]
I was also not accustomed to pytest when I took over this project - and I think the setup of the fixtures is not optimal, but i still gave it a try and it is not completely worthless framework.  
Anyway, you mau add unittests and I ll try to convert them to pytests.

**Comment by mplanchard** [comment]
@ankostis Sorry, when I say unit tests, I meant pytests. I use "unit test" as a generic catchall term for unit tests, pytests, nose tests, etc. Pytest is fantastic, and any tests we add should use the pytest framework.

**Pull request merged**
