### PR TITLE
Use “pip download” instead of “pip install -d” for pip >= 10

### LINKED ISSUE #214: pypi-server -Ux command executes pip install -d which is not supported anymore
Error:
```
Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -d
```

pip Version: 18
pypi-server Version: 1.2.2

Workaround: Installing pip Version 9

### PR DESCRIPTION
**Pull request by elboerto**
Resolves #214

Debugging of pypi-server -Ux execution of pip install -d which has been replaced by pip download since version 10.0.0

I fixed the issue by checking the pip version. If pip version is >= 10.0.0 the command pip download will be used instead of pip install.

### CODE REVIEW

**Comment by mplanchard** [comment]
Thanks for the PR! Would you be comfortable adding a test for this? If not, I can write a test and open a PR against your branch.

**Comment by elboerto** [comment]
Would be awesome if you could write a test.

**Comment by mplanchard** [comment]
I’ll get that done this evening!

**Comment by mplanchard** [comment]
Okay, maybe not this evening. It wound up being movie night 😁 

I will definitely get it done by the end of the weekend, though, and feel free to bug me if I don't!

**Comment by mplanchard** [comment]
@elboerto I opened elboerto/pypiserver#1 adding tests to your contribution! Once that's merged, we'll be good to go here.

**Comment by mplanchard** [comment]
Fix released in v1.2.4 🎉 🎊

**Pull request merged**
