### PR TITLE
chore(package-release-from-gh-actions): Adding release management to GitHub actions

### PR DESCRIPTION
**Pull request by dee-me-tree-or-love**
> It's a work in progress 🏗️ More details will follow soon, but all comments and suggestions are already welcome! ✌️ 

# What

Adding a package deployment on new tags as a GitHub Actions workflow.

## TODOs

- [x] Build the _wheels_ and push to PyPi.
- [x] Build the docker image with the right tags and push it to DockerHub.

## Remarks 

_Working as hard as I can, sorry for all the delays, why and how is this going to work will be described soon, big thanks everyone for all the patience_ ✌️

### CODE REVIEW

**Review by mplanchard — COMMENTED** [review]
Looking good to me! Didn't know there was a github action for this now, that's pretty nice

**Comment by dee-me-tree-or-love** [comment]
Hmmm, that's a curious failing test case... 

All seems to work on local setup, plus have succeeded earlier... Will look into it... Any ideas are very welcome ✌️ 

```plaintext
collected 479 items                                                                                                                                                  

tests/test_app.py ............................................................................................................................................ [ 29%]
...................                                                                                                                                            [ 33%]
tests/test_backend.py ......                                                                                                                                   [ 34%]
tests/test_config.py .............................................................................................................................             [ 60%]
tests/test_core.py ........                                                                                                                                    [ 62%]
tests/test_docs.py .                                                                                                                                           [ 62%]
tests/test_init.py ..............                                                                                                                              [ 65%]
tests/test_main.py ...........................                                                                                                                 [ 70%]
tests/test_manage.py ..............................                                                                                                            [ 77%]
tests/test_pkg_helpers.py .........................................................................................                                            [ 95%]
tests/test_server.py ....................                                                                                                                      [100%]

========================================================================== warnings summary ==========================================================================
```

**Comment by dee-me-tree-or-love** [comment]
Update! The failing tests seem to relate to the seamless update of `setuptools` at the first glance. I found more people (and CI pipelines especially) affected by a similar symptom: https://github.com/pypa/setuptools/issues/3197. I will try to make a fix today and hope to lead the release preps to completion ✌️

**Review by mplanchard — APPROVED** [review]
Looks great! Thanks for taking on the CI wrangling! :rocket:

**Comment by dee-me-tree-or-love** [comment]
Awesome! @mplanchard thanks for the approval 👍 Merged, I will try to cut the release sometime soon!

**Pull request merged**
