### PR TITLE
Feature/markdown conversion

### PR DESCRIPTION
**Pull request by ghinks**

### CODE REVIEW

**Comment by ghinks** [comment]
@dee-me-tree-or-love / @mplanchard 👀 any chance of a review ❓

**Comment by dee-me-tree-or-love** [comment]
Hey @ghinks! Thanks a lot for the ping :)) I'm going to get to the review hopefully this week! From what I've seen already -  awesome work 🙂 Maybe one thing needed is to update the README with release date and version details after the recent 1.5.2 release (if you try to merge `master` one), sorry for any merge conflicts 😅

**Comment by ghinks** [comment]
changes to date and version number made.

**Review by dee-me-tree-or-love — DISMISSED** [review]
@ghinks great work! Thank you so much for fixing this up and carefully following up on all the related doc details. I think it looks good! 

There's only a small formatting mismatch detected in the CI, so if you could fix that, I'll merge it right after! 👍

**Comment by ghinks** [comment]
Many thanks @dee-me-tree-or-love I missed my own markdown check. I fixed it up. After this PR is merged I'll a different PR to make the markdown check show what is wrong. By default mdformat when failing does so without giving any reason.

**Comment by dee-me-tree-or-love** [comment]
> Many thanks @dee-me-tree-or-love I missed my own markdown check. I fixed it up. After this PR is merged I'll a different PR to make the markdown check show what is wrong. By default mdformat when failing does so without giving any reason.

Thanks @ghinks! Really appreciate the great work on this topic! :) Such a follow-up would be really awesome 👍

**Review by dee-me-tree-or-love — APPROVED** [review]
Looking great! Let's go for it, I hope this will make future doc efforts easier 😺 Thanks @ghinks! 🌟

**Pull request merged**
