### PR TITLE
Updated changelog

### PR DESCRIPTION
**Pull request by mplanchard**
Prepping for release

### CODE REVIEW

**Comment by ankostis** [comment]
- I would still call it `1.2.1` - `1.3.0` implies non-backward-compatible changes - where there any?
  (note that `1.2.1` > 1.2.1dev0`  according to PEP 440).
- Can you write the release checklist we discussed, somewhere?  README under some new csection? Inside some script file in `/bin/`?
- Mark the date in CHANGES.
- Accept my PR for `bumpver` script, to use it to engrave the new version.  
- Execute `bumpver`, then `./bin/package.sh`, etc.

**Comment by ankostis** [comment]
I'm adding the checklist in a new `/bin/README.rst` file, in #185.

**Comment by mplanchard** [comment]
Thought you had said you wanted to pop it up to 1.3.0. I'll get the changes in when I finish up work for the day.

**Comment by mplanchard** [comment]
Updated with requested changes.

**Comment by alexntt** [comment]
I know this is a personal project, but is there any plan to make a release? We are using https://github.com/codekoala/docker-pypi and we wonder if we should wait until a new version is released and that project is updated or make permanent fixes to our infrastructure.

Can we help in some way?

**Comment by mplanchard** [comment]
Yes. I apologize. This is always a busy time of year at work. I will have time to get it released this afternoon or evening (CST).

**Comment by mplanchard** [comment]
@alexntt `1.2.1dev0` is now available on PyPI. If all goes well with the pre-release, I'll push a non-pre-release in a few days.

**Comment by alexntt** [comment]
Thanks @mplanchard , no need to apologize! I didn't mean to put pressure or anything- it was just convenient for us to know what the plan was to plan accordingly- but of course we understand that you guys aren't providing a paid service so things advance when they can.

I will try to get the Docker guy to update his container with your prerelease, many thanks! We have hacked our setup to put the right fallback URL- our only interest here is to leave things "clean" again, which is not a big urgency item.

**Comment by mplanchard** [comment]
No problem! I totally understand the difficulties of having to deal with bugs in software that people are maintaining in their free time, and I especially appreciate your offer to help in getting stuff out. It's much easier to feel good about pushing to release something when people are nice about asking for it!

Please let us know if there are any problems with the pre-release. It seems to have been going well so far, so I will probably upgrade it to an "rc" this evening, and plan for a proper release later this week.

**Comment by alexntt** [comment]
Cool! As you might have seen, I've hit https://github.com/pypiserver/pypiserver/issues/175

**Pull request merged**
