### PR TITLE
feat(build): add `/bin/bumpver.py` script to facilitate new releases

### PR DESCRIPTION
**Pull request by ankostis**
A python script to facilitate developers build new releases easily.
You may receive help by executing `./bin/bumpver.py --help`.

### CODE REVIEW

**Comment by ankostis** [comment]
@mplanchard  make some  tests, and ask me for help here.  E.g. with `--amend` you can remain on the same bump-ver commit, with `--force`, you can move a tag created on a previous attempt (or just delete it).

**Comment by ankostis** [comment]
I'm ready here.  Review and merge.

**Comment by mplanchard** [comment]
Sorry for the delay on this. It's a busy week at work (as usual). I will review this over lunch today, though.

**Comment by ankostis** [comment]
You may merge it then, in advance to your Release.

**Pull request merged**
