### PR TITLE
WIP: AppEngine plugin as part of the package

### PR DESCRIPTION
**Pull request by deemetree-at-satelligence**
# What

Based on #322 this adds an implementation of a plugin allowing to use AppEngine and Google Cloud Storage as the pypiserver backend.

> Disclaimer: note that this is a work in progress

## Context 

Opened this merge request with the intention to collaborate closer on proposed code changes and discuss more technical aspects of the implementation.

### TODOs

- [x] Simplify the code
- [x] Ensure build works
- [x] Consider making separate builds for `pypiserver`-core and `pypiserver` with plugin

--- 

#### Remarks: 

- @dee-me-tree-or-love might be pushing commits too

### CODE REVIEW

**Comment by dee-me-tree-or-love** [comment]
@mplanchard hello hello!  
This has been a very very very veeeery long time but it's getting here :) 
I've been unfortunately taken over with a heavy project lately so have not been active in this repository at all. Now should be clearing up and I had a moment to clean it up a bit. 

I think I've kept this PR in progress for quite a while by now, and, maybe, should aim at not trying to get it "complete" and would appreciate a review and suggestions for what it currently is if that's possible :) 

I think there are many ways to improve it still but the basis should be as is :slightly_smiling_face: 

Cheers!

**Comment by elfjes** [comment]
@dee-me-tree-or-love Hey,

We're currently refactoring Pypiserver to be able to support different storage backends (issue #253 and #325, PR  #348). While this approach is very different from your solution, it will make it easier to support GCS buckets fully as pypiserver won't necessarily rely on all packages having to reside on a local filesystem, and makes it possible to implement custom caching solutions for these remote kind of backends to improve performance. Also, since all operations go through a common interface, there's no need custom strategies for change detection. What do you think of the new approach? I would love to hear your opinion on the matter

**Comment by dee-me-tree-or-love** [comment]
Hey @elfjes! Wow, that's actually great news indeed! For some personal reasons I haven't been able to be very much up to date lately, but I will take a look and certainly adjust to the new API's if possible, that would indeed make it much easier! I will also go through the mentioned MR and see if I can fit in a comment or two for the proposals or learn something from the new organization, thanks :)

**Comment by dee-me-tree-or-love** [comment]
> @dee-me-tree-or-love Hey,
> 
> We're currently refactoring Pypiserver to be able to support different storage backends (issue #253 and #325, PR #348). While this approach is very different from your solution, it will make it easier to support GCS buckets fully as pypiserver won't necessarily rely on all packages having to reside on a local filesystem, and makes it possible to implement custom caching solutions for these remote kind of backends to improve performance. Also, since all operations go through a common interface, there's no need custom strategies for change detection. What do you think of the new approach? I would love to hear your opinion on the matter

@elfjes hey hey, I have finally managed to get to go through the alternative storage scenario and the idea and the PR look great! A much more flexible and reusable solution. I think I'll close this MR then now for the sake of waiting for that improvement first. Can I be somehow helpful there? Maybe any specific things I could review? 

But anyhow, great stuff, closing this one for now, I will see whether I will restart it later after your proposal is finished :+1:.

**Pull request closed without merging**
