### PR TITLE
FEAT: Switch default hash-algo to sha256

### LINKED ISSUE #452: Discussion: Should pypiserver switch default hash algorithm to sha256?
Current default configuration of pypiserver does no longer work with poetry >= 1.2 as pypiserver uses md5 by default for hashing. There is an open issue for this here: https://github.com/python-poetry/poetry/issues/6301 (and workaround with using `--hash-algo=sha256` here: https://github.com/python-poetry/poetry/issues/4523#issuecomment-923741164).

This may still be fixed by a future release of poetry. Still I wonder if it would be useful to switch the default hashing algorithm to sha256 as this is current recommendation by PEP 503

>  Repositories SHOULD choose a hash function from one of the ones guaranteed to be available via the hashlib module in the Python standard library (currently md5, sha1, sha224, sha256, sha384, sha512). **The current recommendation is to use sha256.** 

(note: highlight is mine)

Changing the algorithm would be a breaking change

### PR DESCRIPTION
**Pull request by jayeff**
I prepared a PR which switches default hash-algo to sha256 as discussed in #452. Created as draft PR as it probably should not be merged before major version bump to 2.0 is concrete.

Closes #452

### CODE REVIEW

**Comment by dee-me-tree-or-love** [comment]
Hello @jayeff! 😊 Sorry for all the long time it took to get here, but I think we're very [ready for the 2.0.0 release](https://github.com/pypiserver/pypiserver/milestone/8) and I'm really looking forward to merging this PR 🌟 Would you be able to review the merge conflicts to prepare it for merging? 😊 

If you don't have time or are not interested, I'll try to merge your commits into a feature branch and solve any merge issues separately before going to the default branch, I hope that's okay with you too ✌️ 

Let me know if anything!

**Comment by jayeff** [comment]
No problem. If this works for you I can look at it next week

**Comment by dee-me-tree-or-love** [comment]
> No problem. If this works for you I can look at it next week

yes, absolutely! Thanks a lot @jayeff. Take your time and if you need any help, feel free to ping me.

**Comment by jayeff** [comment]
@dee-me-tree-or-love Merge conflicts are resolved can PR can be reviewed now 👍

**Review by dee-me-tree-or-love — APPROVED** [review]
This is awesome! Thanks a lot @jayeff, looking forward to merging it 🎉

**Comment by dee-me-tree-or-love** [comment]
> @dee-me-tree-or-love Merge conflicts are resolved can PR can be reviewed now 👍

Amazing, thanks a lot for your effort @jayeff, this is looking very good

**Pull request merged**
