### PR TITLE
chore(ver): bump 1.2.1.dev0-->1.2.1dev1

### PR DESCRIPTION
**Pull request by mplanchard**

### CODE REVIEW

**Comment by ankostis** [comment]
Approve...oups!  wouldn't you like to name it `1.2.1rc0`?

**Comment by mplanchard** [comment]
Hm. I was thinking we might ensure no more bugs popped up before bumping it to RC status, but I think you're probably right. Might as well push it through.

**Comment by ankostis** [comment]
```
git reset --hard HEAD~
git tag -d 1.2.1.dev1
./bin/bumpver 1.2.1rc0 ...
```

**Comment by mplanchard** [comment]
Closing and re-opening to keep the branch name accurate.

**Pull request closed without merging**
