### PR TITLE
Added /search action

### PR DESCRIPTION
**Pull request by psaavedra**
In reply of https://github.com/pypiserver/pypiserver/issues/80#issuecomment-191975405

### CODE REVIEW

**Comment by mplanchard** [comment]
Looks like existing tests failed. I'd also like to see a unit test for this new functionality before we merge.

**Comment by ankostis** [comment]
Is python-2 only syntax included in this PR?

```
  File "./pypi-server-standalone.py/pypiserver/_app.py", line 248
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by mplanchard** [comment]
Thank you for your contribution! However, I vote we focus on adding search via #114, which parses the XML in a more Pythonic, low maintenance way. If you would like to contribute to that PR (possibly a unit test, which is still required), please feel free to do so.

**Comment by mplanchard** [comment]
Handled via #114, which has been merged.

**Pull request closed without merging**
